version: "3.8"

volumes:
  healthcare_data: {}

services:
  db:
    image: postgres:alpine3.18
    container_name: health-care-db
    restart: always
    networks:
      - proxy
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - healthcare_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: health-care-adminer
    networks:
      - proxy
    restart: always
    ports:
      - 8082:8080
  
  express:
    build:
      context: ./
    container_name: health-care-express
    restart: always
    volumes:
      - ./backend:/home/node/app
    networks:
      - proxy
    expose:
      - 3000
    # ports:
    #   - '3000:3000'
    # command: 'npm start'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.express.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.express.entrypoints=websecure"
      - "traefik.http.routers.express.tls.certresolver=myresolver"
  
networks:
  proxy:
    external: true